server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: Eureka-Server

  security:
    user:
      name: yangonion
      password: 123456