management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always