server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: Server-Provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/